- name: Update all packages
  dnf:
    name: "*"
    state: latest

- name: Install EPEL and required tools
  dnf:
    name:
      - epel-release
      - firewalld
    state: present

- name: Enable and start firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Open HTTP port
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Open HTTPS port
  firewalld:
    port: 443/tcp
    permanent: true
    state: enabled
    immediate: true

# ────── K3s Support Ports (only when k3s_enabled is true) ──────
- name: Open K3s API port (6443)
  firewalld:
    port: 6443/tcp
    permanent: true
    state: enabled
    immediate: true
  when: k3s_enabled | default(false)

- name: Open Kubelet API port (10250)
  firewalld:
    port: 10250/tcp
    permanent: true
    state: enabled
    immediate: true
  when: k3s_enabled | default(false)

- name: Open Flannel VXLAN port (8472/udp)
  firewalld:
    port: 8472/udp
    permanent: true
    state: enabled
    immediate: true
  when: k3s_enabled | default(false)

- name: Open Traefik NodePorts (30080-30443) only from LB subnet
  firewalld:
    rich_rule: >
      rule family="ipv4"
      source address="10.0.1.0/24"
      port port="30080-30443" protocol="tcp" accept
    permanent: true
    state: enabled
    immediate: true
  when: k3s_enabled | default(false)