name: "Ansible Runner"
description: "Reusable step to run Ansible playbooks"
inputs:
  host:
    required: true
    description: "Target host ip"
  user:
    required: true
    description: "SSH user"
  playbook:
    required: true
    description: "Playbook to run (relative to ansible/playbooks/)"
  ssh_key:
    required: true
    description: "SSH private key"
  extra_vars:
    required: false
    description: "Extra vars string (quoted)"

runs:
  using: "composite"
  steps:
    - name: Install Ansible
      shell: bash
      run: |
        sudo apt-get install -y ansible

    - name: Setup SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ inputs.host }} >> ~/.ssh/known_hosts

    - name: Run Ansible Playbook
      shell: bash
      run: |
        cd ansible
        if [ -n "${{ inputs.extra_vars }}" ]; then
          EXTRA_VARS="--extra-vars \"${{ inputs.extra_vars }}\""
        else
          EXTRA_VARS=""
        fi
        ansible-playbook playbooks/${{ inputs.playbook }} \
          -i "${{ inputs.host }}," \
          -u "${{ inputs.user }}" \
          --private-key ~/.ssh/id_rsa \
          --become \
          $EXTRA_VARS
