- name: Setup K3s master
  hosts: all
  become: true
  vars:
    k3s_enabled: tru
    duckdns_domain: "{{ duckdns_domain }}"
    duckdns_token: "{{ duckdns_token }}"
    acme_email: "{{ acme_email }}"
  roles:
    - common
    - k3s
