- name: Update DuckDNS IP
  ansible.builtin.uri:
    url: "https://www.duckdns.org/update?domains={{ duckdns_domain }}&token={{ duckdns_token }}&ip="
    method: GET
    return_content: true
  register: duckdns_response

- name: Show DuckDNS update response
  ansible.builtin.debug:
    var: duckdns_response.content

- name: Ensure Traefik config directory exists
  ansible.builtin.file:
    path: "/opt/traefik"
    state: directory
    owner: opc
    group: opc
    mode: '0755'

- name: Create acme.json file (empty, secure)
  ansible.builtin.copy:
    content: ""
    dest: /opt/traefik/acme.json
    owner: opc
    group: opc
    mode: '0600'

- name: Create traefik.yml
  ansible.builtin.template:
    src: "traefik.yml.j2"
    dest: /opt/traefik/traefik.yml
    owner: opc
    group: opc
    mode: '0644'

- name: Ensure Docker network exists
  ansible.builtin.shell: |
    docker network inspect app_network >/dev/null 2>&1 || docker network create app_network
  become: true
  become_user: opc

- name: Deploy Traefik
  include_tasks: "../../common/tasks/setup-compose-app.yml"
  vars:
    compose_app_path: "/opt/traefik"
    compose_template: "traefik-docker-compose.yml.j2"

- name: Wait for Traefik to be ready
  ansible.builtin.uri:
    url: http://localhost:80
    status_code: 404
    timeout: 10
    validate_certs: false
  register: traefik_check
  retries: 10
  delay: 5
  until: traefik_check is succeeded

- name: Deploy Job Winner app
  include_tasks: "../../common/tasks/setup-compose-app.yml"
  vars:
    compose_app_path: "/opt/jobwinner"
    compose_template: "jobwinner-docker-compose.yml.j2"
