- name: Update DuckDNS IP
  ansible.builtin.uri:
    url: "https://www.duckdns.org/update?domains={{ duckdns_domain }}&token={{ duckdns_token }}&ip="
    method: GET
    return_content: true
  register: duckdns_response

- name: Show DuckDNS update response
  ansible.builtin.debug:
    var: duckdns_response.content

- name: Deploy Traefik
  include_tasks: "../../common/tasks/setup_compose_app.yml"
  vars:
    compose_app_path: "/opt/traefik"
    compose_template: "docker-compose.yml.j2"

- name: Deploy Job Winner app
  include_tasks: "../../common/tasks/setup_compose_app.yml"
  vars:
    compose_app_path: "/opt/jobwinner"
    compose_template: "docker-compose.yml.j2"
