- name: Remove podman if present
  dnf:
    name: podman
    state: absent

- name: Install Docker dependencies
  dnf:
    name: dnf-plugins-core
    state: present

- name: Add Docker repository
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add opc user to docker group
  user:
    name: opc
    groups: docker
    append: yes
