name: Set up Traefik

on:
  workflow_dispatch:
    inputs:
      host:
        description: "Target host IP"
        type: string
        required: true
      user:
        description: "SSH user"
        type: string
        required: true
        default: opc
      traefik_host_domain:
        description: "Traefik host domain"
        type: string
        required: true
        default: "jobwinner.duckdns.org"

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Ansible Playbook to set up Traefik
        uses: ./.github/actions/ansible-runner
        with:
          host: ${{ inputs.host }}
          user: ${{ inputs.user }}
          ssh_key: ${{ secrets.OCI_PRIVATE_KEY }}
          playbook: setup-traefik.yml
          extra_vars: |
            acme_email=${{ secrets.DUCKDNS_EMAIL }}
            traefik_host_domain=${{ inputs.traefik_host_domain }}
