name: Set up K3s

on:
  workflow_dispatch:
    inputs:
      host:
        description: "Target host IP"
        required: true
        type: string
      user:
        description: "SSH user"
        required: true
        type: string
        default: opc
      lb_ip:
        description: "Load Balancer IP"
        required: true
        type: string

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Ansible Playbook to set up K3s
        uses: ./.github/actions/ansible-runner
        with:
          host: ${{ inputs.host }}
          user: ${{ inputs.user }}
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          playbook: setup-k3s.yml
          extra_vars: duckdns_domain=janusc acme_email=${{ secrets.DUCKDNS_EMAIL }} duckdns_token=${{ secrets.DUCKDNS_TOKEN }} ip_lb=${{ inputs.lb_ip }} flannel_iface=enp0s6
